NOME: GUILHERME MENDES DE OLIVEIRA


1a)

In [19]:
import numpy as np

def calculaNorma(m):

    W = np.random.rand(m,4)
    W2 = W/np.sqrt(m)
    Z = W2.transpose()@W2
    print (Z)
    n = np.linalg.norm((Z-np.identity(4)),'fro')
    return n

1b)

In [ ]:
calculaNorma(1000)
print('\n')
calculaNorma(10000)

1c)


Podemos dizer que essa matriz após ser decrescida de sua média é centralizada e após ser dividida pela sua norma é Normalizada


2a)

In [18]:
x = np.array([1, 2, 3])
u = np.array([1, 1, 0])
v = np.array([1, -1, 1])

#Normalizando os vetores
uT = u.T/np.linalg.norm(u.T,2)
vT = v.T/np.linalg.norm(v.T,2)
xT = x.T/np.linalg.norm(x.T,2)

#Calculando a projeção (Produto Interno de X vezes vetor Base/ Norma 2 da Base)
xU = np.dot(xT,uT)/np.linalg.norm(u.T,2)*xT
xV = np.dot(xT,vT)/np.linalg.norm(v.T,2)*xT

print(xU)
print(xV)

[0.10714286 0.21428571 0.32142857]
[0.04761905 0.0952381  0.14285714]
[0.1547619  0.30952381 0.46428571]


2b)

Porque essa recomposição leva em consideração apenas dois eixos do vetor para ter uma recomposição exata precisaria de um outro vetor Base para ser gerado um eixo Z

3)

In [20]:
dados = np.array ([[90, 80, 60, 95],
               [65, 75, 90, 70],
               [40, 90, 60, 55],
               [80, 60, 59, 75],
               [60, 100, 80, 80]
              ])
#Calculo de Média e do Desvio Padrão das linhas
mu = np.mean(dados,axis=0)
sigma2 = np.var(dados,axis=0,ddof=1)

#Dados Centralizados
dadosCenter = dados - mu


#Dados Normalizados 
dadosNorm = dadosCenter/np.sqrt(sigma2)

#Matriz Covariancia
m,n = dadosNorm.shape
dadosCov = dadosNorm.T@dadosNorm /(m - 1)
#dadosCov = np.cov(dadosNorm)
np.set_printoptions(precision=3 )
dadosCov

array([[ 1.   , -0.566, -0.193,  0.869],
       [-0.566,  1.   ,  0.254, -0.085],
       [-0.193,  0.254,  1.   , -0.06 ],
       [ 0.869, -0.085, -0.06 ,  1.   ]])

4)

V
V
F
F
F
F